require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'BusinessIntelligence' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Charts'
  pod 'TinyConstraints'

  target 'BusinessIntelligenceTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'BusinessIntelligence-tvOS' do
  # Pods for BusinessIntelligence-tvOS

  target 'BusinessIntelligence-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|

    # fix firebase error https://github.com/invertase/react-native-firebase/issues/2780
    system('cd Pods/Headers/Public; ln -s Protobuf protobuf')

    # fix build warnings
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end

  end
end